language: python
python:
  - stable

before_install:
  - pip install robotframework
  - pip install robotframework-seleniumlibrary

install: true

before_script:
    - python3 -m http.server

script:
  - pybot login_tests
