language: python

addons:
  firefox: "55.0.3"

before_install:
  - pip install -r requirements.txt
  - pip install robotframework
  - pip install robotframework-seleniumlibrary

install: true

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - cd demoapp/html
  - python3 -m http.server &
  - sleep 3
  - cd -
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar zxvf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

script:
  - pybot login_tests
