language: java
jdk:
- openjdk8

addons:
  firefox: "55.0.3"

before_install:
  - pip install robotframework
  - pip install robotframework-seleniumlibrary

before_script:
  - pybot demoapp/server.py &
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar zxvf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

script:
  - pybot login_tests
