language: python

dist: trusty
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost

before_install:
    - pip install -r login_tests/requirements.txt
    - pip install robotframework
    - pip install robotframework-seleniumlibrary

install: true


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - robot login_tests
